--- 
pid: tmp/pids/thin.pid
wait: 30
timeout: 30
log: log/thin.log
max_conns: 1024
require: []

max_persistent_conns: 512
environment: production
servers: 5
daemonize: true
chdir: /d/mac/1/sburq/work/mars_site
socket: /tmp/thin.mars_prod.sock
